version: "2"

# A Docker Compose file for configuration of the development environment

services:
  # load balancer
  nginx-lb:
    #image: docker-nginx-lb:demo
    image: hq.hoplasoftware.com:7443/jramirez/hopla-loadbalancer:demo
    container_name: nginx-lb
    restart: unless-stopped
    networks:
      - simplest-nodeapp-lb-demo-net
    ports:
      - "8181:80"

  simplest-nodeapp:
    #image: alpine-docker-simplest-nodeapp:demo
    image: hq.hoplasoftware.com:7443/jramirez/hopla-simplest-nodeapp:demo
    restart: unless-stopped
    networks:
       simplest-nodeapp-lb-demo-net:
        aliases:
          - simplest-nodeapp
    expose:
      - 3000
    depends_on:
      - nginx-lb

networks:
  simplest-nodeapp-lb-demo-net: {}
